// Generated by CoffeeScript 1.6.3
(function() {
  var cc;

  cc = function() {
    var arg, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = arguments.length; _i < _len; _i++) {
      arg = arguments[_i];
      _results.push(console.log(arg));
    }
    return _results;
  };

  $(function() {
    var $people, checkHeight, flash, goToPage, hash, len, objectflasher, personindex;
    checkHeight = function() {
      if ($("body").height() < $(window).height()) {
        return $("header").removeClass("hidden-header");
      }
    };
    goToPage = function(page, $el) {
      var $g, $link, $t, i, rel;
      $t = $el || $(this);
      rel = page || $t.attr("rel");
      $g = $("#" + $t.parent().data("group"));
      $link = $("#" + rel);
      if ($t.hasClass("slider")) {
        return;
      }
      if ($link.hasClass("active-page")) {
        return;
      }
      $g.children().hide().removeClass("active-page");
      if (typeof rel === "undefined") {
        i = $t.index();
        $g.children().eq(i).fadeIn("fast").addClass("active-page");
      }
      $g.children().removeClass("active-page");
      $link.fadeIn("fast");
      $link.addClass("active-page").trigger("viewingpage");
      $(".selected-tab").removeClass("selected-tab");
      $t.addClass("selected-tab");
      if ($t.parent().attr("hashchange") !== "false") {
        window.location.hash = rel;
        $('html, body').animate({
          scrollTop: 0
        }, 400);
      }
      return checkHeight();
    };
    $(".tabs").on("click", "li", function() {
      return goToPage.call(this);
    });
    $(".tabs li").each(function() {
      var $g, $t;
      $t = $(this);
      if (!$t.index()) {
        $t.addClass("selected-tab");
      }
      $g = $("#" + $t.parent().data("group"));
      $g.children(":gt(0)").hide();
      return $g.children().first().addClass("active-page").trigger("viewingpage");
    });
    hash = window.location.hash;
    if (hash !== "") {
      goToPage.call($("[rel=" + hash.slice(1) + "]"), hash.slice(1));
    }
    $(window).scroll(function() {
      if ($(window).scrollTop() > 0) {
        $("header").removeClass("hidden-header");
        return $("body").addClass("header-visible");
      } else {
        $("header").addClass("hidden-header");
        return $("body").removeClass("header-visible");
      }
    });
    $(".js-goto").on("click", "a", function(e) {
      var loc, pos;
      loc = $(this).attr("href");
      pos = $(loc).offset().top;
      $('html, body').animate({
        scrollTop: pos - 70 + "px"
      }, 400);
      return e.preventDefault();
    });
    $("#contact").on("viewingpage", function() {
      return $(this).find("input").first().focus().select();
    });
    objectflasher = function() {
      var $spottedobj, arr, len, objindex;
      $spottedobj = $(".js-spotted-object");
      objindex = 0;
      arr = ["toys", "Santa", "his new apartment", "birds flying high", "Jay-Z", "Kanye", "a white Christmas"];
      len = arr.length;
      return function() {
        return $spottedobj.fadeOut("fast", function() {
          $(this).text(arr[objindex % len]).fadeIn("fast");
          return objindex++;
        });
      };
    };
    setInterval(objectflasher(), 6000);
    $people = $(".person-image");
    len = $people.length;
    personindex = 0;
    flash = function() {
      $(".saturated").removeClass("saturated");
      $people.eq(personindex % len).addClass("saturated");
      return personindex++;
    };
    flash();
    return setInterval(flash, 5000);
  });

  $(window).on("hashchange", function() {
    var hash, pages;
    pages = ["contact", "help", "home", "blog", "team"];
    hash = window.location.hash.slice(1);
    if (pages.indexOf(hash) !== -1) {
      $("html, body").finish();
      return $("[rel=" + hash + "]").trigger("click");
    }
  });

}).call(this);
